In [6]:
import numpy as np

In [2]:
a1 = np.array(["Spark", "Hadoop", "Python","R"])

In [3]:
a1

array(['Spark', 'Hadoop', 'Python', 'R'], dtype='<U6')

In [4]:
a2 = np.array([['Altura', 'Largura', 'Profundidade'],[42,78,10]])

In [5]:
a2

array([['Altura', 'Largura', 'Profundidade'],
       ['42', '78', '10']], dtype='<U12')

In [7]:
a2.shape

(2, 3)

In [10]:
a1.ndim
a2.ndim

2

In [13]:
a3 = np.array([[10,20,30],[40,50,60]])
a3.max()

60

In [16]:
array = np.arange(0,100,10)
array

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
matriz = np.zeros((10,10))
matriz

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [2]:
b = np.array([10,10,20,30])
b.dtype

dtype('int64')

In [4]:
e = np.array([False, False, True])
e.dtype

dtype('bool')

In [6]:
array = np.arange(0,5) * 10
array

array([ 0, 10, 20, 30, 40])

In [16]:
arrayA = np.arange(0,10)
arrayB = np.arange(0,10)+1

In [18]:
arrayA
arrayB
arrayA > arrayB

array([False, False, False, False, False, False, False, False, False,
       False])

In [20]:
A = np.array([2,4,6])
B = np.array([2,2,2])
A*B

array([ 4,  8, 12])

In [22]:
A = np.arange(10)
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [1]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autocall  %automagic  %autosave  %bookmark  %cat  %cd  %clear  %colors  %config  %connect_info  %cp  %debug  %dhist  %dirs  %doctest_mode  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %lf  %lk  %ll  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %lx  %macro  %magic  %man  %matplotlib  %mkdir  %more  %mv  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %popd  %pprint  %precision  %profile  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %rep  %rerun  %reset  %reset_selective  %rm  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python

In [3]:
%timeit 3 + 1

21.4 ns ± 0.42 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [5]:
def soma(a,b):
    num1 = a
    num2 = b
    resultado =  a + b
    return resultado

In [ ]:
a = [1,2,11,6,18]