In [1]:
import numpy as np

In [4]:
A = [[1,2,3,4],[5,6,7,8],[10,20,30,40],[50,60,70,80]]
array = np.array(A)
print(array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [5]:
print(array[2])

[10 20 30 40]


In [8]:
print(array[0,-1])

4


In [9]:
array[0,0] = 0
print(array)

[[ 0  2  3  4]
 [ 5  6  7  8]
 [10 20 30 40]
 [50 60 70 80]]


In [10]:
print(array[-1,:])

[50 60 70 80]


In [ ]:
A = np.array([1,2], [3,4])
B = np.array([5,6])

In [12]:
X = np.matrix([[1,2],[3,4]])
Y = np.matrix([[5,3],[8,7]])

Z = np.array()

In [14]:
print(type(X))

<class 'numpy.matrixlib.defmatrix.matrix'>


In [16]:
A1 = np.array([[10,20,30],[40,50,60]])

In [18]:
A1.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [20]:
np.transpose(A1)

array([[10, 40],
       [20, 50],
       [30, 60]])

In [21]:
A2 = np.array([[100,200,300]])

In [25]:
A3 = A2.T + A2

In [27]:
A3.ravel()

array([200, 300, 400, 300, 400, 500, 400, 500, 600])